### ISSUE TITLE
我拉了php5，用你云编译项目，不知道我是否配置正确，请你帮忙看一下https://github.com/dzhuqi/Actions-OpenWrt

### ISSUE THREAD

**Issue by dzhuqi** [P3TERX/Actions-OpenWrt#1]
我拉了php5，用你云编译项目，不知道我是否配置正确，请你帮忙看一下https://github.com/dzhuqi/Actions-OpenWrt

**Comment by P3TERX** [comment]
😂云编译这叫法还行。
`git clone`后面路径中的`packages`要去掉最后的`s`。我之前改了脚本工作路径，教程里的忘记改了。

**Comment by dzhuqi** [comment]
噢噢
