### ISSUE TITLE
请教如何取消默认勾选的软件

### ISSUE THREAD

**Issue by caolixiang** [P3TERX/Actions-OpenWrt#117]
例如我希望取消ddns 
在配置中(.config)文件中加入了
#CONFIG_DEFAULT_luci-app-ddns is not set
#CONFIG_PACKAGE_luci-app-ddns is not set 
但编译后，ddns还在，类似还有adbyby-plus

**Comment by hungleung** [comment]
是不是该把前面的   #   去掉

**Comment by caolixiang** [comment]
> 是不是该把前面的 # 去掉

显然不是，我也知道#，代表注释。
终于试成功了。答案是
# CONFIG_PACKAGE_luci-app-ddns is not set 
#与CONFIG之间必须有空格

**Comment by caolixiang** [comment]
resolved
