### ISSUE TITLE
奶牛快传好像url拼接有问题什么的还是下载解压有问题，系统是ubuntu-latest

### ISSUE THREAD

**Issue by yinzhefuyun** [P3TERX/Actions-OpenWrt#125]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     72      0 --:--:-- --:--:-- --:--:--    71
100     9  100     9    0     0     72      0 --:--:-- --:--:-- --:--:--    71

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
##[error]Process completed with exit code 2.

**Comment by ClayMoreBoy** [comment]
同样出现这个问题 @P3TERX

**Comment by P3TERX** [comment]
![image](https://user-images.githubusercontent.com/25927179/78757557-43166400-79af-11ea-8700-e5cf03eb088a.png)
