### ISSUE TITLE
SSH connection to Actions无法展开

### ISSUE THREAD

**Issue by Longhorn3683** [P3TERX/Actions-OpenWrt#132]
我想在云编译中使用ssh，但是SSH connection to Actions进行时无法展开

**Comment by meloncn** [comment]
> 我想在云编译中使用ssh，但是SSH connection to Actions进行时无法展开

这个问题我也发现了就是当执行到此步骤时如果没有及时展开此选项或者刷新页面后无法显示控制后台内容。我的做法是修改了ssh Actions那个调用仓库的配置文件让他每30秒钟打印一次打印n遍。这样及时你没有来得及展开，只需要在规定时间内访问即可弹出
