### ISSUE TITLE
如何增加SSR Plus

### ISSUE THREAD

**Issue by Troyshen94** [P3TERX/Actions-OpenWrt#142]
L大的最新源码隐藏了SSR Plus
想请教一下 现在要怎么设置可以自动编译的时候加上SSR Plus

**Comment by qxzg** [comment]
https://github.com/P3TERX/Actions-OpenWrt/pull/138

**Comment by Troyshen94** [comment]
> #138

感谢大佬! 我照着这个操作 成功编译进去了~！
