### ISSUE TITLE
通过 web­hook 关键词触发 GitHub Ac­tions报错

### ISSUE THREAD

**Issue by bin20088** [P3TERX/Actions-OpenWrt#144]
按你的步骤改了那四个参数，:owner，:repo，ACTIONS_TRIGGER_TOKEN，TRIGGER_KEYWORDS。但是一直报错，具体设置及错误请看图。
![QQ截图20200425164833](https://user-images.githubusercontent.com/53508344/80275555-9eb55100-8714-11ea-8340-48cc2f723735.jpg)
![photo_2020-04-25_16-46-06](https://user-images.githubusercontent.com/53508344/80275558-a2e16e80-8714-11ea-810a-b66ce82d6e2e.jpg)
![photo_2020-04-25_16-46-10](https://user-images.githubusercontent.com/53508344/80275560-a543c880-8714-11ea-9f4d-70af86ae6e53.jpg)

**Comment by P3TERX** [comment]
填 token 不是 token 名称。
