### ISSUE TITLE
请问是否只有UPLOAD_FIRMWARE为true才能上传到奶牛或者WETRANSFER？

### ISSUE THREAD

**Issue by pirately** [P3TERX/Actions-OpenWrt#153]
请问是否只有UPLOAD_FIRMWARE为true才能上传到奶牛或者WETRANSFER？
即，如果单独设置UPLOAD_COWTRANSFE或者UPLOAD_WETRANSFER为true，但是UPLOAD_FIRMWARE: false，实际上奶牛或者WETRANSFER不能上传？
能否设置成不上传到GitHub本身的actions，只上传到奶牛等？

**Comment by garypang13** [comment]
> 能否设置成不上传到GitHub本身的actions，只上传到奶牛等？

可以的

**Comment by pirately** [comment]
> > 能否设置成不上传到GitHub本身的actions，只上传到奶牛等？
> 
> 可以的

请问，怎么实现？因为我在GitHub私有仓库设置UPLOAD_FIRMWARE: false，后续的UPLOAD_COWTRANSFE或者UPLOAD_WETRANSFER就算设置成true，都没有上传。

**Comment by garypang13** [comment]
把第118行 if: env.UPLOAD_FIRMWARE == 'true' && !cancelled() 删掉即可

**Comment by pirately** [comment]
> 把第118行 if: env.UPLOAD_FIRMWARE == 'true' && !cancelled() 删掉即可

感谢，我试试

**Comment by Hey-Leo** [comment]
> 把第118行 if: env.UPLOAD_FIRMWARE == 'true' && !cancelled() 删掉即可

似乎不删除，把`&&`换成`||`更好一点

**Comment by Hey-Leo** [comment]
### 在build-openwrt.yml中
> Organize files （line127）

-  删掉 `if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()` ，

 
>Upload firmware directory （line 136）

-  `if: steps.organize.outputs.status == 'success' && !cancelled()` 改为 `if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()`
