### ISSUE TITLE
出错 Check failure on line 1 in .github  @github-actions github-actions / build  .github#L1 No space left on device

### ISSUE THREAD

**Issue by y162287761** [P3TERX/Actions-OpenWrt#159]
请问出现
 Check failure on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
No space left on device

 Check failure on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
Process completed with exit code 2.

 Check warning on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
Failed to remove 'http.https://github.com/.extraheader' from the git config

请问出现这些错误怎么解决

**Comment by aizhouyi** [comment]
我也是这样的错误，七八次了。
no space left on device

**Comment by yangxiangguo** [comment]
我也是  如何解决

**Comment by CORE2021** [comment]
同样！空间不足了？

**Comment by Itxiaoniao** [comment]
Check failure on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
No space left on device

**Comment by aizhouyi** [comment]
我在lean那里看到同样的issue了！！！源码问题？

**Comment by P3TERX** [comment]
最近 Actions 做了一些改动，把工作目录挂载到了 14G 临时分区，所以导致了空间不足。

不过这个改动导致了一些问题（与空间不足无关），今天已经回滚了，所以目前已经**暂时**恢复到了可正常编译 OpenWrt 的状态。

actions/virtual-environments#709
coolsnowwolf/lede#4654

**Comment by aizhouyi** [comment]
编译成功了，今天。感谢回答原因。
