### ISSUE TITLE
Process completed with exit code 255.老是报错

### ISSUE THREAD

**Issue by xiangfeigao** [P3TERX/Actions-OpenWrt#163]
老是报错，Process completed with exit code

是哪里的原意
1
Fri, 05 Jun 2020 07:39:09 GMT
Run sudo swapoff /swapfile
23
Fri, 05 Jun 2020 07:39:09 GMT
swapoff: /swapfile: swapoff failed: No such file or directory
24
Fri, 05 Jun 2020 07:39:09 GMT
##[error]Process completed with exit code 255.

**Comment by Hey-Leo** [comment]
> Initialization environment

- 删掉 `sudo swapoff /swapfile` （第52行）试试

**Comment by xiangfeigao** [comment]
> > Initialization environment
> 
> * 删掉 `sudo swapoff /swapfile` （第52行）试试

问题依旧

**Comment by Hey-Leo** [comment]
> > > Initialization environment
> > 
> > 
> > 
> > * 删掉 `sudo swapoff /swapfile` （第52行）试试
> 
> 问题依旧

把第53行的 `/swapfile`也删了看看
