### ISSUE TITLE
编译参数只读取到了SUBTARGET，具体的DEVICE没能读取出来，导致把所有的包都编译出来了

### ISSUE THREAD

**Issue by victoratmaoludotone** [P3TERX/Actions-OpenWrt#185]
配置文件中指定了：
CONFIG_TARGET_BOARD="ramips"
CONFIG_TARGET_SUBTARGET="mt7621"
CONFIG_TARGET_PROFILE="DEVICE_ubiquiti_edgerouterx"
但编译结果将所有的mt7621的设备固件都编译出来了。

**Comment by ccbcfan** [comment]
two

**Comment by ccbcfan** [comment]
发现是config文件格式发生变化，解决办法是：ssh下 make menuconfig选择上传的.config，重新设定编译的机型，再保存后就可正常编译指定固件了。
