### ISSUE TITLE
生成的固件压缩包中没有squashfs-sysupgrade.bin文件

### ISSUE THREAD

**Issue by zsymljxzcy** [P3TERX/Actions-OpenWrt#198]
只有version.buildinfo、sha256sums、.manifest、initramfs-kernel.bin、feeds.buildinfo、config.buildinfo这6个文件

**Comment by wsltshh** [comment]
选的功能超过固件大小，超容了

**Comment by zsymljxzcy** [comment]
请问有办法解决么？

**Comment by wsltshh** [comment]
你看是不是超容了，是的话少*标点啊

**Comment by zsymljxzcy** [comment]
明白了，貌似选择$$R功能就会出现这样的问题，看来要放弃它了
谢谢你

**Comment by zsymljxzcy** [comment]
但是我看其他人选择$$R功能好像也都没有问题，是不是和选择的路由型号有关（我选的是K2P）
