### ISSUE TITLE
服务下找不到v2ray/ss

### ISSUE THREAD

**Issue by HCrSn** [P3TERX/Actions-OpenWrt#201]
我编译了以后找不到v2ray/ss，但是软件包里显示已安装。我试过了`echo 0xDEADBEEF > /etc/config/google_fu_mode`但菜单里还是没有选项。

[.config.txt](https://github.com/P3TERX/Actions-OpenWrt/files/5120773/default.config.txt)

**Comment by qinfeng8848** [comment]
diy-part1.sh
# Uncomment a feed source
sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default

**Comment by HCrSn** [comment]
已解决，之前看到过这一条，怀疑自己是不是傻
