### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by abc2251259** [P3TERX/Actions-OpenWrt#215]
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..7b6163f3364f163d1bece2ded057173c3c4340e4
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..7b6163f3364f163d1bece2ded057173c3c4340e4

#
# configuration written to .config
#
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..7b6163f3364f163d1bece2ded057173c3c4340e4
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..7b6163f3364f163d1bece2ded057173c3c4340e4
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..7b6163f3364f163d1bece2ded057173c3c4340e4
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..7b6163f3364f163d1bece2ded057173c3c4340e4

没有影响编译结果，但是请问下这个有什么遗留问题吗？

**Comment by P3TERX** [comment]
这个不影响编译
