### ISSUE TITLE
这两周开始编译失败，找不到  P3TERX/debugger-action/tarball/master

### ISSUE THREAD

**Issue by renwairen** [P3TERX/Actions-OpenWrt#224]
An action could not be found at the URI 'https://api.github.com/repos/P3TERX/debugger-action/tarball/master'
一直好好的，最近两周开始这个错误了

**Comment by steveny5997** [comment]
我这里出现一样的错误，求助大神

**Comment by VergilGao** [comment]
因为repo主把master分支重命名为了main
所以要手动把ci里的`P3TERX/debugger-action@master`改成`P3TERX/debugger-action@main`

**Comment by steveny5997** [comment]
> 因为repo主把master分支重命名为了main
> 所以要手动把ci里的`P3TERX/debugger-action@master`改成`P3TERX/debugger-action@main`

感谢！解决了！

**Comment by renwairen** [comment]
> 因为repo主把master分支重命名为了main
> 所以要手动把ci里的`P3TERX/debugger-action@master`改成`P3TERX/debugger-action@main`

啊  多谢  我试试去
