### ISSUE TITLE
Action could not be found.

### ISSUE THREAD

**Issue by JeroGC** [P3TERX/Actions-OpenWrt#227]
Download action repository 'actions/checkout@master'
Download action repository 'P3TERX/debugger-action@master'
Error: An action could not be found at the URI 'https://api.github.com/repos/P3TERX/debugger-action/tarball/master'

**Comment by mryuanxiaojun** [comment]
同上错误，大神有解决方法吗？

**Comment by mryuanxiaojun** [comment]
把build-openwrt.yml里的   
   - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
改为如下内容：
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@main

就是把@后面的master改为main。
受到https://github.com/P3TERX/debugger-action的readme.md的启发。 不知道是不是这个原因，目前编译能运行了！
