### ISSUE TITLE
The `set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by yang123me** [P3TERX/Actions-OpenWrt#230]
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by VergilGao** [comment]
46行
master改成main # 见鬼的zzzq

**Comment by yang123me** [comment]
建议截图说明

羽先生 <notifications@github.com> 于2020年10月6日周二 上午9:26写道：
