### ISSUE TITLE
如何开启SSH连接呢?

### ISSUE THREAD

**Issue by molun** [P3TERX/Actions-OpenWrt#237]
ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

false全部修改为ture吗?

**Comment by Dimitri2020007** [comment]
不需要，在你打开workflow的时候填true就是了

**Comment by molun** [comment]
> 不需要，在你打开workflow的时候填true就是了

![image](https://user-images.githubusercontent.com/23138506/96360691-d0eabd00-1151-11eb-9b7b-a5674913cb5d.png)
会自动跳过，有没有配置实例呢

**Comment by Dimitri2020007** [comment]
修改脚本

**Comment by mzxwt** [comment]
> 修改脚本，这个教程里有的

我也遇到同样问题，请大佬指点！

**Comment by leo8912** [comment]
![image](https://user-images.githubusercontent.com/22719866/96413183-e2010000-121d-11eb-8d65-ae06601c65ef.png)

**Comment by shizihang** [comment]
以前的版本改成true就行，现在的版本改成true之后会自动跳过

**Comment by molun** [comment]
亲测star触发也会跳过，按照leo8912的图解可以

**Comment by dandanhuiyi** [comment]
SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
![image](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)

但是点击cancel 之后,可以看到.
![image](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)

**Comment by kousyougi** [comment]
> SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> ![image](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> 
> 但是点击cancel 之后,可以看到.
> ![image](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)

我遇到一樣的狀況，之前SSH connection to Actions那欄可以正常顯示。現在要手動cancel之後才會顯示出來。

**Comment by kousyougi** [comment]
> SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> ![image](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> 
> 但是点击cancel 之后,可以看到.
> ![image](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)

![build](https://user-images.githubusercontent.com/43228565/100464686-01d2f000-3109-11eb-888c-b2f0066d7f9a.png)
我剛剛試著點Chrome的開發人員工具，想看是不是什麼東西沒載入成功。一按之後SSH connection to Actions的細節就跳出來的。而且可以很明顯看到，前面的1~71的信息被截斷了，畫面從72開始顯示。

**Comment by knowsai** [comment]
> > SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> > ![image](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> > 但是点击cancel 之后,可以看到.
> > ![image](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)
> 
> ![build](https://user-images.githubusercontent.com/43228565/100464686-01d2f000-3109-11eb-888c-b2f0066d7f9a.png)
> 我剛剛試著點Chrome的開發人員工具，想看是不是什麼東西沒載入成功。一按之後SSH connection to Actions的細節就跳出來的。而且可以很明顯看到，前面的1~71的信息被截斷了，畫面從72開始顯示。

同样actions run的时候遇到问题，但是我这边直接是不显示的，点击开发者工具并不显示。回去查看了P3TERX的更新历史，在10月11号的时候更新了SSH connect 的组件引用。改回去旧版的引用就好。
![image](https://user-images.githubusercontent.com/22045048/100578631-a9287080-331d-11eb-9f26-b3fff79e688a.png)

**Comment by kousyougi** [comment]
> > > SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> > > 但是点击cancel 之后,可以看到.
> > 
> > 
> > 我剛剛試著點Chrome的開發人員工具，想看是不是什麼東西沒載入成功。一按之後SSH connection to Actions的細節就跳出來的。而且可以很明顯看到，前面的1~71的信息被截斷了，畫面從72開始顯示。
> 
> 同样actions run的时候遇到问题，但是我这边直接是不显示的，点击开发者工具并不显示。回去查看了P3TERX的更新历史，在10月11号的时候更新了SSH connect 的组件引用。改回去旧版的引用就好。


我剛剛改過去測試。目前改之前跟改之後都是時好時壞。有時候會顯示，有時候不會顯示。

**Comment by knowsai** [comment]
> > > > SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> > > > 但是点击cancel 之后,可以看到.
> > > 
> > > 
> > > 我剛剛試著點Chrome的開發人員工具，想看是不是什麼東西沒載入成功。一按之後SSH connection to Actions的細節就跳出來的。而且可以很明顯看到，前面的1~71的信息被截斷了，畫面從72開始顯示。
> > 
> > 
> > 同样actions run的时候遇到问题，但是我这边直接是不显示的，点击开发者工具并不显示。回去查看了P3TERX的更新历史，在10月11号的时候更新了SSH connect 的组件引用。改回去旧版的引用就好。
> 
> 我剛剛改過去測試。目前改之前跟改之後都是時好時壞。有時候會顯示，有時候不會顯示。
参考一下我新改的，用了P3TERX的SSH2ACTIONS。
![image](https://user-images.githubusercontent.com/22045048/100624440-6fc42500-335e-11eb-82d3-d44574828f48.png)

**Comment by shizihang** [comment]
看这个样子像是 把链接发送到telegram了

**Comment by molun** [comment]
> 看这个样子像是 把链接发送到telegram了

不用telegram的话，把他注释掉！
亲测绑定的话，telegram会先于页面收到消息

**Comment by idonotneedname** [comment]
> SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> ![image](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> 
> 但是点击cancel 之后,可以看到.
> ![image](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)

run  workflow以后进入日志页面，在进行到ssh之前的任意一步把最左边的箭头点开，显示滚动详情，这样到ssh的时候就能第一时间刷新出连接信息，ssh信息会滚动10次，之后就不再滚动，如果你错过了这段时间不点开详情，等它跑完10次以后就点不出来了，今天折腾了半天来回弄了好几次才发现这个办法

**Comment by kobayashiming** [comment]
> > SSH连接到操作改成真正的时候，运行到SSH的时候就卡住了，SSH的连接信息无法输出在日志中，
> > ![图片](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> > 但是点击取消之后，可以看到。
> > ![图片](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)
> 
> 运行工作流以后进入日志页面，在进行到ssh之前的任意一步把最左边的箭头点开，显示滚动详情，这样到ssh的时候可以第一时间刷新出连接信息，ssh信息会滚动10次，之后就不再滚动，如果你错过了这段时间不点开详情，等它跑完10次以后就点不出来了，今天折腾了半天来回弄了好几次才发现这个办法

好像不行，还是不显示

**Comment by knowsai** [comment]
> > > SSH连接到操作改成真正的时候，运行到SSH的时候就卡住了，SSH的连接信息无法输出在日志中，
> > > ![图片](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> > > 但是点击取消之后，可以看到。
> > > ![图片](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)
> > 
> > 
> > 运行工作流以后进入日志页面，在进行到ssh之前的任意一步把最左边的箭头点开，显示滚动详情，这样到ssh的时候可以第一时间刷新出连接信息，ssh信息会滚动10次，之后就不再滚动，如果你错过了这段时间不点开详情，等它跑完10次以后就点不出来了，今天折腾了半天来回弄了好几次才发现这个办法
> 
> 好像不行，还是不显示

经楼上的提示，其实要去看P3TERX的SSH2ACTIONS的逻辑，ssh2actions的代码里面应该是telegram优先接收的信息。可以fork这个库下来，修改为自己的库地址，然后把telegram的内容注释掉就好。

**Comment by shizihang** [comment]
把推送改成server酱的话会好点吧 tg用着不方便

**Comment by knowsai** [comment]
> 把推送改成server酱的话会好点吧 tg用着不方便

请问怎么换呢？

**Comment by Licolnlee** [comment]
> 
> 
> > 看这个样子像是 把链接发送到telegram了
> 
> 不用telegram的话，把他注释掉！
> 亲测绑定的话，telegram会先于页面收到消息

想请教下怎么绑定telegram

**Comment by shanghaiqw** [comment]
> > SSH connection to Actions 改为true 的时候, run 到SSH的时候就卡住了,SSH的连接信息 无法输出在log 中,
> > ![image](https://user-images.githubusercontent.com/3646105/99179164-d4279780-2755-11eb-9347-2c46ccca8272.png)
> > 但是点击cancel 之后,可以看到.
> > ![image](https://user-images.githubusercontent.com/3646105/99179233-a68f1e00-2756-11eb-8f13-7c33a9ffbe0b.png)
> 
> 我遇到一樣的狀況，之前SSH connection to Actions那欄可以正常顯示。現在要手動cancel之後才會顯示出來。

你可你试试 在卡住的时候 右上角搜索下https 就会出来的
