### ISSUE TITLE
请教新功能使用方法

### ISSUE THREAD

**Issue by molun** [P3TERX/Actions-OpenWrt#238]
secrets.TELEGRAM_CHAT_ID
secrets.TELEGRAM_BOT_TOKEN
secrets.GITHUB_TOKEN

是要在Settings>>Secrets中创建名称为TELEGRAM_CHAT_ID、TELEGRAM_BOT_TOKEN、GITHUB_TOKEN的密钥值吗？

**Comment by Gladtbam** [comment]
`TELEGRAM_CHAT_ID和TELEGRAM_BOT_TOKEN`是可选参数，作用是把ssh参数发送到telegram，可以删掉，`GITHUB_TOKEN`在右上角的setting创建
![image](https://user-images.githubusercontent.com/49943258/97263900-d5ecf200-185e-11eb-9fe5-2306000a6f5d.png)
