### ISSUE TITLE
不能定时运行

### ISSUE THREAD

**Issue by lexin8** [P3TERX/Actions-OpenWrt#239]
name: Build OpenWrt

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - 'x86.config'
  schedule:
    - cron: 40 10 * * *
  watch:
    types: started

代码入上，10:40不会自动触发运行，是哪里没设置好吗？

**Comment by Gladtbam** [comment]
这个时间是GMT标准时间，北京时间10：40应该是GMT时间2：40，改成40 2 * *  *``

**Comment by Gladtbam** [comment]
这个时间是GMT标准时间，北京时间10：40应该是GMT时间2：40，改成`40 2 * * *`
