### ISSUE TITLE
文件名填写为.config，把生成的.config 文件的内容复制粘贴到下面的文本框中。--这个文件在那里看的

### ISSUE THREAD

**Issue by talway** [P3TERX/Actions-OpenWrt#249]
教程文档咨询：
https://p3terx.com/archives/build-openwrt-with-github-actions.html
文件名填写为.config，把生成的.config 文件的内容复制粘贴到下面的文本框中。--

请问这个文件在那里看的

**Comment by jokefrelon** [comment]
把L大源码clone下来以后，进入目录，`make menuconfig `生成的，主要就是指定你需要的固件平台和软件

**Comment by talway** [comment]
明白了，感谢！

**Comment by yangme123** [comment]
【教程】用GitHub Actions云编译
https://github.com/coolsnowwolf/lede/issues/2288
