### ISSUE TITLE
请问重新编译时一直卡在load custom configuration是什么原因

### ISSUE THREAD

**Issue by fyhong** [P3TERX/Actions-OpenWrt#260]
![op](https://user-images.githubusercontent.com/24217040/102001343-12e84780-3d2c-11eb-9ab2-ce4526960727.jpg)
一直卡在这一步半天不过去。什么原因

**Comment by Evenjine** [comment]
同问

**Comment by winona2021** [comment]
我也碰到的同样的问题，第一次编译成功后，之后的每次编译都是卡在了“ssh connection to actions”，一直都不动
