### ISSUE TITLE
ActionsRML/delete-workflow-runs被移除

### ISSUE THREAD

**Issue by eanucc** [P3TERX/Actions-OpenWrt#269]
ActionsRML/delete-workflow-runs被移除，需要找个替代的脚本。否则，云编译脚本无法运行，在setup a job就会出现问题。

**Comment by houandy** [comment]
同样的问题，有解决方案没

**Comment by NagaseKouichi** [comment]
没法编译了

**Comment by NagaseKouichi** [comment]
把ActionsRML/delete-workflow-runs@main那部分注释掉了，貌似可以编译

**Comment by smallprogram** [comment]
Change to smallprogram/delete-workflow-runs@main

**Comment by Myoko** [comment]
> Change to smallprogram/delete-workflow-runs@main

这个方法可行 ！ 现在可以编译了 ！感谢

**Comment by eanucc** [comment]
谢谢各位大佬！

**Comment by eanucc** [comment]
> Change to smallprogram/delete-workflow-runs@main

谢谢大侠！
