### ISSUE TITLE
编译过程中报错，请问如何解决？

### ISSUE THREAD

**Issue by sdc9088** [P3TERX/Actions-OpenWrt#275]
Failed to resolve action download info. Error: Unable to resolve action `P3TERX/debugger-action@master`, repository not found

**Comment by 281677160** [comment]
你没有更新脚本啊，还是老的，你这个显示没找到最新的SSH脚本库（老的P3TERX/debugger-action@master）（新的P3TERX/ssh2actions@v1.0.0）

**Comment by sdc9088** [comment]
谢谢，我来试试
