### ISSUE TITLE
/home/runner/work/_temp/01ec4b2b-9e6b-41c6-bb30-f8d893841205.sh: line 1: cd: openwrt/bin/targets/*/*: No such file or directory Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by moqingzhu1** [P3TERX/Actions-OpenWrt#276]
每次都是这样，大佬分析一下
/home/runner/work/_temp/01ec4b2b-9e6b-41c6-bb30-f8d893841205.sh: line 1: cd: openwrt/bin/targets/*/*: No such file or directory
Error: Process completed with exit code 1.

**Comment by francis5959** [comment]
之前还好好的，突然出现和你一样的问题，全新编译几次均未成功，已放弃

**Comment by shmily103** [comment]
> 之前还好好的，突然出现和你一样的问题，全新编译几次均未成功，已放弃

看看前面的错误。前面编译没成功。所以没有文件。
