### ISSUE TITLE
大佬，编译openwrt卡到这里不动了

### ISSUE THREAD

**Issue by aabbcc582** [P3TERX/Actions-OpenWrt#280]
Run P3TERX/ssh2actions@v1.0.0
[INFO] Setting up tmate ...
[INFO] You may need to enter a password to authorize.

[INFO] Check the architecture ...
[INFO] Check the version of tmate ...
[INFO] Download tmate ...
[INFO] tmate download successful !
[INFO] Installation tmate ...
[INFO] tmate successful installation !
[INFO] Running tmate...[](url)
![image](https://user-images.githubusercontent.com/59761506/105946652-a1c5df00-60a2-11eb-9dcb-079e249d3ee4.png)
![image](https://user-images.githubusercontent.com/59761506/105946665-a8eced00-60a2-11eb-9892-44745188cd81.png)

**Comment by bikizz** [comment]
同样的问题，昨天编译可以跳链接，今天试了一直卡

**Comment by winona2021** [comment]
我也碰到了一样的问题，一个新的repo，编译成功过一次之后，之后的每次编译都卡在了“ssh connect to actions”

**Comment by superabbite1** [comment]
我也是卡ssh
