### ISSUE TITLE
从大前天开始用博主的代码云编老是出错。

### ISSUE THREAD

**Issue by lamhui** [P3TERX/Actions-OpenWrt#293]
如题，之前怎么弄都很顺利的就从大前天开始就开始云编失败了，所有加入的插件代码和选项都一模一样之前的都成功大前天开始就编译出错失败了。然后结果提示以下代码：
Annotations
1 error
build: .github#L1
Process completed with exit code 2.

有知道什么原因或者遇到相同问题的朋友吗？你们是如何解决的？

**Comment by hn315** [comment]
删除项目，重新使用大佬这个模版，能够成功。
