### ISSUE TITLE
这个文件怎么改了没用feeds.conf.default

### ISSUE THREAD

**Issue by gethappy555** [P3TERX/Actions-OpenWrt#297]
在根目录上传了修改的文件，但是编译的时候还是用源码库自带的

**Comment by qpmcool** [comment]
教程里说，要把源码里的删除一下。用DIY的脚本改。

**Comment by lanfenglin** [comment]
> 在根目录上传了修改的文件，但是编译的时候还是用源码库自带的

新建一个任务运行试试，原来的任务删除
