### ISSUE TITLE
固件上传到wetransfer网盘不可用

### ISSUE THREAD

**Issue by lariboo** [P3TERX/Actions-OpenWrt#299]
这几天云编译的固件不能上传到wetransfer网盘，提示fetching upload tickets..getSendConfig(single mode) returns error: no csrf-token found。大佬可有解决方法？不胜感谢！

**Comment by HiGarfield** [comment]
同样遇到这个问题。

**Comment by jiawm** [comment]
也遇到了，至今不不能上传，希望老大解决一下
