### ISSUE TITLE
请教，咱们这支持SERVER酱或者推送加吗？

### ISSUE THREAD

**Issue by drw2005** [P3TERX/Actions-OpenWrt#300]
有没有配置方面的说明？好像没看到在哪里，哪位大佬给指点指点，谢谢！

**Comment by Wodrei** [comment]
在workflow中添加相应步骤，参考https://github.com/yakumioto/serverchan-action

**Comment by Wodrei** [comment]
> 有没有配置方面的说明？好像没看到在哪里，哪位大佬给指点指点，谢谢！

在workflow中添加相应步骤，参考https://github.com/yakumioto/serverchan-action

**Comment by fmbfmbhh** [comment]
有可以直接安装的ipk
https://github.com/tty228/luci-app-serverchan

**Comment by firkerword** [comment]
> 有没有配置方面的说明？好像没看到在哪里，哪位大佬给指点指点，谢谢！

可以推送   需要推送秘钥
