### ISSUE TITLE
前几天开始，一直没有编译成功。

### ISSUE THREAD

**Issue by wwowwyu** [P3TERX/Actions-OpenWrt#312]
[](ur
![photo_2021-05-16_07-17-50](https://user-images.githubusercontent.com/31385233/118380763-df7d5200-b616-11eb-9abb-61d79153777b.jpg)
l)重新FORK模版也不可以，没有找到原因

**Comment by AdorableJiang** [comment]
我遇到了同样的问题，是在创建了.config文件之后的一次编译出现的

**Comment by cqlwhu** [comment]
我也遇到了同样的问题

**Comment by wwowwyu** [comment]
***@***.***交流
cqlwhu ***@***.***>于2021年5月30日 周日23:57写道：
