### ISSUE TITLE
openwrt无线中继是不是有问题？

### ISSUE THREAD

**Issue by lamhui** [P3TERX/Actions-OpenWrt#319]
如题，次级路由（K2P，OP系统）通过5G WIFI扫描想无线中继上级路由信号（K2P，同固件的OP系统），操作一切都正常可是提交并保存应用以后在网络--无线下5G项出现 “无线未开启或未关联” 这个问题怎么破有？ 相同方式无线中继用高恪没问题但没有IPV6所以放弃，老毛子还没试但是老毛子没有图形监控设备流量界面所以不得不放弃，LEAN的潘多拉也可以正常中继可是没有IPV6功能也不得不放弃。现疑惑的是这问题出自哪的？是OP本身存在的缺陷(包括但不限于开源闭源驱动。加个题外话，能从无线的界面或者版本号猜出固件里集成的是开源还是闭源的驱动吗？)，还是设置问题还是其它因素导致的？有知道的大神或者遇到过并解决的兄弟帮忙帮忙分析原因或者给予解决方案，感谢！

以下为现象截图和固件版本截图。

网络---无线选项
![image](https://user-images.githubusercontent.com/76201983/122398356-60c85b80-cfac-11eb-86b4-28ff01cee6bf.png)

固件版本
![image](https://user-images.githubusercontent.com/76201983/122398391-6b82f080-cfac-11eb-95db-065569cde65b.png)

**Comment by lxl6125** [comment]
无线中继还是用老毛子吧，op即使中继上也是速度减半
