### ISSUE TITLE
SS Plus编译的时候找不到 

### ISSUE THREAD

**Issue by sk007** [P3TERX/Actions-OpenWrt#323]
已经设置了
sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
上一个月还可以使用
今天不能编译的时候找不到了

**Comment by lonelysoul** [comment]
按我的代码改一下就可以了。
把替换改为新增。

**Comment by sk007** [comment]
> 按我的代码改一下就可以了。
> 把替换改为新增。

可以了 谢谢！
