### ISSUE TITLE
Lean openwrt的编译环境18.04变成了20.04，action的编译环境还是18.04

### ISSUE THREAD

**Issue by felixxiao99** [P3TERX/Actions-OpenWrt#324]
Lean openwrt的编译环境18.04变成了20.04，希望action也做对应的调整

**Comment by Dimitri2020007** [comment]
jobs:
  build:
    runs-on: ubuntu-18.04

将runs-on: ubuntu-18.04改成runs-on: ubuntu-latest就是最新的系统
