### ISSUE TITLE
云 menuconfig--SSH时luci里面没有git仓库的插件

### ISSUE THREAD

**Issue by authon** [P3TERX/Actions-OpenWrt#63]
diy.sh的设置如下

#!/bin/bash
#=================================================
# Description: DIY script
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================
# Modify default IP
#sed -i 's/192.168.1.1/192.168.50.5/g' package/base-files/files/bin/config_generate
git clone https://github.com/Lienol/openwrt-package.git

代码是这样的，想加入passwall，luci里面没有，是这个样设置错了还是需要在build-openwrt.yml进行其他设置

**Comment by P3TERX** [comment]
最后要加上更新 feeds 的命令，仔细看教程，这都有写的。
```
./scripts/feeds update -a
./scripts/feeds install -a
```
