### ISSUE TITLE
最近两天编译都不能完成，是哪里出了问题？

### ISSUE THREAD

**Issue by wtrong** [P3TERX/Actions-OpenWrt#68]
time: package/lean/qBittorrent/compile#0.59#0.19#0.75
make[2]: *** [package/lean/qBittorrent/compile] Error 2
make[1]: *** [/home/runner/work/actions/actions/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make: *** [world] Error 2
/home/runner/work/actions/actions/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
##[error]Process completed with exit code 2.

**Comment by wtrong** [comment]
是利用你的这个脚本的action编译的，应该是最新版本的。

**Comment by garypang13** [comment]
lean源码的问题,那边已经修复了,
