### ISSUE TITLE
一个建议当SSH_ACTIONS: true，自动将.config文件复制一份到openwrt/bin/targets/*/*目录下

### ISSUE THREAD

**Issue by yinzhefuyun** [P3TERX/Actions-OpenWrt#76]
一个建议当SSH_ACTIONS: true，自动将.config文件复制一份到openwrt/bin/targets/*/*目录下，这样就可以把.config文件下载下来了，这样下次编译把这个文件上传github上去就好了，不用再用那个云ssh

**Comment by P3TERX** [comment]
固件目录下有个`config.seed`文件，下次编译可以用。

**Comment by yinzhefuyun** [comment]
> 固件目录下有个`config.seed`文件，下次编译可以用。

是把这个文件改成.config就可以吗？
