### ISSUE TITLE
在release里面添加tag后，actions开始自动编译，编译完成以后zip文件怎么自动同步到tag标签下？

### ISSUE THREAD

**Issue by kemaguagua** [P3TERX/Actions-OpenWrt#86]
请问在release里面添加tag后，actions开始自动编译，编译完成以后zip文件怎么自动同步到tag标签下？

**Comment by P3TERX** [comment]
首先你要了解 GitHub Actions 的基础知识，然后去找一个上传 release 功能的 action ，最后把相关的代码写到 workflow 文件中。
