### ISSUE TITLE
files 目录结构是怎么样对应 openwrt

### ISSUE THREAD

**Issue by wedone** [P3TERX/Actions-OpenWrt#90]
> Custom files（自定义文件）
> 俗称 “files 大法”，在仓库根目录下新建 files 目录，把文件放入即可。

请问 @P3TERX 大，files 目录结构是怎么样对应 openwrt
是下面这样的结构吗？
```
├── files
│   ├── bin/
│   ├── boot/
│   ├── dev/
│   ├── etc/
│   ├── ...
```

**Comment by lujimmy** [comment]
是的。
我一般SSH登陆路由后，使用_scp -R roo@192.168.0.198:/etc/config /User/jimmy/Desktop_来将配置文件夹备份到本地。
编译新固件时，在files文件夹下依次建立目录/etc/config放入名为network、wireless、firewall的三个文件，这样编译的出固件在刷入后会自动配置好，开机即用，很方便。

**Comment by jiayouzl** [comment]
> 是的。
> 我一般SSH登陆路由后，使用_scp -R roo@192.168.0.198:/etc/config /User/jimmy/Desktop_来将配置文件夹备份到本地。
> 编译新固件时，在files文件夹下依次建立目录/etc/config放入名为network、wireless、firewall的三个文件，这样编译的出固件在刷入后会自动配置好，开机即用，很方便。

不错的方法以后试试~
