### ISSUE TITLE
两大错误

### ISSUE THREAD

**Issue by LockeJet** [P3TERX/Actions-OpenWrt#95]
如题，首次编译，出现两大错误：
- Update feeds
> fatal: unable to access 'https://git.openwrt.org/feed/routing.git/': The requested URL returned error: 504
- Organize files
> /home/runner/work/_temp/2231f4dd-4459-48b3-9707-46cc4be92471.sh: line 1: cd: openwrt/bin/targets/*/*: No such file or directory
> ##[error]Process completed with exit code 1.
 
源码问题？

**Comment by P3TERX** [comment]
用的人太多导致 GitHub 服务器炸了
